# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Create the 'windows_2012_r2' vagrant box with https://github.com/joefitzgerald/packer-windows
  config.vm.box = "windows_2012_r2_sysprepvm_gvlk_v2"

  config.vm.network "private_network", ip: "192.168.50.14"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end

  config.vm.provision "file", source: "install-diego.ps1", destination: "C:\\diego-kit\\intall-diego.ps1"

  config.vm.provision "shell", inline: <<-SHELL
    & C:\\diego-kit\\intall-diego.ps1
    echo "Diego Windows setup finished"
  SHELL
end
